# Each new term in the Fibonacci sequence is generated by adding
# the previous two terms.
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued
# items.

$fib = []
$fib[1] = 1
$fib[2] = 2

for n in (3..100)
  $fib[n] = $fib[n-1] + $fib[n-2] 
  if $fib[n] >= 4_000_000
    $fib.pop
    break
  end
end

$fib = $fib.compact
$fib = $fib.select { |n| n.even? }
puts $fib.inject(:+)



